language: python
python:
    - "2.7"
services:
    - elasticsearch

before_install:
    - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb && sudo dpkg -i elasticsearch-1.2.1.deb && sudo service elasticsearch restart


install: "pip install -r requirements.txt"

script: nosetests
