language: python
python:
    - "2.7"

services:
  - elasticsearch

install: "pip install -r dev-requirements.txt"

before_script: "cp scrapi/settings/travis-dist.py scrapi/settings/local.py"

script: py.test tests
