language: python
sudo: false
python:
    - "2.7"
    - "3.5"

services:
  - cassandra
  - elasticsearch
  - postgres

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/wheelhouse

env:
  - WHEELHOUSE=$HOME/wheelhouse

install:
  - travis_retry pip install -U invoke==0.11.1 coveralls
  - travis_retry invoke wheelhouse --develop
  - travis_retry invoke requirements --develop
  - cp scrapi/settings/travis-dist.py scrapi/settings/local.py

before_script:
  - flake8 .
  - psql -c "CREATE DATABASE scrapi;" -U postgres
  - python manage.py migrate

script:
  - invoke provider_map
  - invoke test

after_success:
  coveralls

notifications:
  flowdock: df4d2322a6b6ec2c086c8b6b22f4abed
