language: python
python:
    - "2.7"

services:
  - cassandra
  - elasticsearch

install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - cp scrapi/settings/travis-dist.py scrapi/settings/local.py

before_script: flake8 .

script:
  - invoke provider_map
  - invoke test

after_success:
  coveralls
