---

days: 'mon-fri'
hour: 13
minute: 45

directory: 'ClinicalTrials'

name: 'Clinical Trials Registry'

git-url: 'https://github.com/erinspace/ClinicalTrials-consumer.git'
    
file-format: '.xml'

...